"""initial schema

Revision ID: 1403186caa00
Revises: 
Create Date: 2026-07-12 12:44:17.269188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1403186caa00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_schema',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('field_set_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_set_json', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_field_set_templates_signature', 'field_set_templates', ['signature'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_set_signature', sa.String(), nullable=False),
    sa.Column('column_signature', sa.String(), nullable=False),
    sa.Column('mapping_json', sa.Text(), nullable=False),
    sa.Column('structural_hint_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_set_signature', 'column_signature')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('canonical_field',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('schema_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('allowed_values_json', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min', sa.Double(), nullable=True),
    sa.Column('max', sa.Double(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['canonical_schema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'name'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_canonical_field_schema_id'), 'canonical_field', ['schema_id'], unique=False)
    op.create_table('alias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('canonical_field_id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('source_column', sa.String(), nullable=False),
    sa.Column('provenance_kind', sa.String(), nullable=False),
    sa.Column('provenance_actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_field_id'], ['canonical_field.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_field_id', 'vendor', 'source_column'),
    sa.UniqueConstraint('seq')
    )
    op.create_index(op.f('ix_alias_canonical_field_id'), 'alias', ['canonical_field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alias_canonical_field_id'), table_name='alias')
    op.drop_table('alias')
    op.drop_index(op.f('ix_canonical_field_schema_id'), table_name='canonical_field')
    op.drop_table('canonical_field')
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_index('idx_field_set_templates_signature', table_name='field_set_templates')
    op.drop_table('field_set_templates')
    op.drop_table('canonical_schema')
    # ### end Alembic commands ###
